global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['monitoring-app:8081']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: [ 'elasticsearch:9200' ]
    metrics_path: '/_prometheus/metrics'